name: build-windows

on:
  push:
    branches: [ main ]         
    tags: [ 'v*' ]              
  release:
    types: [published]         
  workflow_dispatch:           
    inputs:
      tag:
        description: 'Tag to build & attach (e.g. v1.1.0)'
        required: false

permissions:
  contents: write               

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build EXE
        run: npx electron-builder --win --x64 --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
      - name: List outputs
        shell: pwsh
        run: |
          Write-Host "=== dist ==="
          Get-ChildItem -Recurse -File dist | Select-Object FullName
          Write-Host "=== out/make ==="
          Get-ChildItem -Recurse -File out\make 2>$null | Select-Object FullName

    
      - name: Upload artifact (.exe)
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: |
            dist/**/*.exe
            out/make/**/*.exe
          if-no-files-found: error   


      - name: Attach to GitHub Release
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*.exe
            out/make/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
