name: Build Windows and Mac App

on:
  push:
    branches:
      - main   # main 브랜치에 push할 때 실행

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Windows EXE
        run: npm run build -- --win

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: dist/*

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Mac App
        run: npm run build -- --mac

      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-app
          path: dist/*
